// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjF1i03l_Dfk35nB4JOEPKSQjWXrijZNk',
    appId: '1:577748585756:web:ff3100085225e58efb3ed9',
    messagingSenderId: '577748585756',
    projectId: 'skin-2f2d2',
    authDomain: 'skin-2f2d2.firebaseapp.com',
    storageBucket: 'skin-2f2d2.firebasestorage.app',
    measurementId: 'G-XFETY8DCJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOjJpz6_Ict0AkUBKxLBh7HU8XsAg3tI',
    appId: '1:577748585756:android:862339f223e8a971fb3ed9',
    messagingSenderId: '577748585756',
    projectId: 'skin-2f2d2',
    storageBucket: 'skin-2f2d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApCmRVupkHjnBXBlBpcFyV4oGc3Oxr-jM',
    appId: '1:577748585756:ios:be3eda6ff75dc3defb3ed9',
    messagingSenderId: '577748585756',
    projectId: 'skin-2f2d2',
    storageBucket: 'skin-2f2d2.firebasestorage.app',
    iosBundleId: 'com.example.skin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApCmRVupkHjnBXBlBpcFyV4oGc3Oxr-jM',
    appId: '1:577748585756:ios:be3eda6ff75dc3defb3ed9',
    messagingSenderId: '577748585756',
    projectId: 'skin-2f2d2',
    storageBucket: 'skin-2f2d2.firebasestorage.app',
    iosBundleId: 'com.example.skin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjF1i03l_Dfk35nB4JOEPKSQjWXrijZNk',
    appId: '1:577748585756:web:3f8c3c67fed85a37fb3ed9',
    messagingSenderId: '577748585756',
    projectId: 'skin-2f2d2',
    authDomain: 'skin-2f2d2.firebaseapp.com',
    storageBucket: 'skin-2f2d2.firebasestorage.app',
    measurementId: 'G-76MPRK2FM1',
  );
}
